### ISSUE TITLE
No OpenGL

### ISSUE THREAD

**Issue by xNemesis733o13** [ate47/Xray#20]
![image](https://user-images.githubusercontent.com/86566203/123551916-c914fb00-d76b-11eb-9b29-640e577db691.png)
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 27/06/21 16:41
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:ForgeHaxCore:default,xf:ForgeHaxCore:default,pl:mixin:APP:assets/offhandcombat/offhandcombat.mixins.json:RightClickMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$16609/1561946928.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:429) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:ForgeHaxCore:default,xf:ForgeHaxCore:default,pl:mixin:APP:assets/offhandcombat/offhandcombat.mixins.json:RightClickMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$14461/825525122.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,xf:ForgeHaxCore:default,xf:ForgeHaxCore:default,pl:mixin:APP:origins.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:ForgeHaxCore:default,xf:ForgeHaxCore:default,pl:mixin:APP:assets/offhandcombat/offhandcombat.mixins.json:RightClickMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:ForgeHaxCore:default,xf:ForgeHaxCore:default,pl:mixin:APP:assets/offhandcombat/offhandcombat.mixins.json:RightClickMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$525/810898134.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:378) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
-- MOD atianxray --
Details:
	Mod File: ForgeXray-1.0.5-1.16.x.jar
	Failure message: XrayMod (atianxray) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	Mod Version: 1.0.5
	Mod Issue URL: https://github.com/ate47/Xray/issues
	Exception message: java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
Stacktrace:
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:378) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:322) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at com.simibubi.create.foundation.render.backend.Backend.refresh(Backend.java:102) ~[?:mc1.16.5_v0.3.1c+151] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.handler$zjk000$refresh(WorldRenderer.java:6127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_72712_a(WorldRenderer.java:994) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,pl:mixin:A}
	at fr.atesab.xray.XrayMain.modules(XrayMain.java:149) ~[?:1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at fr.atesab.xray.XrayMain.saveConfigs(XrayMain.java:335) ~[?:1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at fr.atesab.xray.XrayMain.loadConfigs(XrayMain.java:258) ~[?:1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at fr.atesab.xray.XrayMain.setup(XrayMain.java:449) ~[?:1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at fr.atesab.xray.XrayMain$$Lambda$7939/777722039.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2980/1502606003.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2610/534192621.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3445/467043101.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 663689648 bytes (632 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
		/ForgeHax-1.16.5-3.3.1-ddd237c.jar ForgeHaxCore TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.12.1
	Mod List: 
		mowziesmobs-1.5.16.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.16              |SIDED_SETU|NOSIGNATURE
		DungeonsMod-1.16.3-1.3.20.jar                     |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.3.20       |SIDED_SETU|NOSIGNATURE
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |SIDED_SETU|45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |SIDED_SETU|NOSIGNATURE
		Hats-1.16.5-10.3.0.jar                            |Hats                          |hats                          |10.3.0              |SIDED_SETU|NOSIGNATURE
		Bountiful+Baubles+FORGE-1.16.3-0.0.2.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |SIDED_SETU|NOSIGNATURE
		jei-1.16.4-7.6.1.74.jar                           |Just Enough Items             |jei                           |7.6.1.74            |SIDED_SETU|NOSIGNATURE
		AttributeFix-1.16.5-10.1.2.jar                    |AttributeFix                  |attributefix                  |10.1.2              |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |SIDED_SETU|NOSIGNATURE
		ProjectE-1.16.5-PE1.0.1B.jar                      |ProjectE                      |projecte                      |PE1.0.1B            |SIDED_SETU|NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |SIDED_SETU|NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.0.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.0      |SIDED_SETU|NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|SIDED_SETU|NOSIGNATURE
		Waystones_1.16.5-7.4.0.jar                        |Waystones                     |waystones                     |7.4.0               |SIDED_SETU|NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |SIDED_SETU|NOSIGNATURE
		CookingForBlockheads_1.16.5-9.3.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.2               |SIDED_SETU|NOSIGNATURE
		Placebo-1.16.4-4.4.5.jar                          |Placebo                       |placebo                       |4.4.5               |SIDED_SETU|NOSIGNATURE
		comforts-forge-1.16.5-4.0.0.4.jar                 |Comforts                      |comforts                      |1.16.5-4.0.0.4      |SIDED_SETU|NOSIGNATURE
		citadel-1.6.3.jar                                 |Citadel                       |citadel                       |1.6.3               |SIDED_SETU|NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |SIDED_SETU|NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |SIDED_SETU|NOSIGNATURE
		culinaryconstruct-forge-1.16.5-4.0.0.6.jar        |Culinary Construct            |culinaryconstruct             |1.16.5-4.0.0.6      |SIDED_SETU|NOSIGNATURE
		charginggadgets-1.3.0.jar                         |Charging Gadgets              |charginggadgets               |1.3.0               |SIDED_SETU|NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |SIDED_SETU|d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		buildinggadgets-1.16.4-3.7.3.jar                  |Building Gadgets              |buildinggadgets               |3.7.3               |SIDED_SETU|NOSIGNATURE
		Apotheosis-1.16.4-4.6.0.jar                       |Apotheosis                    |apotheosis                    |4.6.0               |SIDED_SETU|NOSIGNATURE
		mahoutsukai-1.16.5-v1.31.3.jar                    |Mahou Tsukai                  |mahoutsukai                   |1.16.5-v1.31.3      |SIDED_SETU|NOSIGNATURE
		iceandfire-2.1.6-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.6-1.16.4        |SIDED_SETU|NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |SIDED_SETU|NOSIGNATURE
		iChunUtil-1.16.5-10.4.0.jar                       |iChunUtil                     |ichunutil                     |10.4.0              |SIDED_SETU|NOSIGNATURE
		mininggadgets-1.7.1.jar                           |Mining Gadgets                |mininggadgets                 |1.7.1               |SIDED_SETU|NOSIGNATURE
		ForgeHax-1.16.5-3.3.1-ddd237c.jar                 |ForgeHax                      |forgehax                      |3.3.1-ddd237c       |SIDED_SETU|NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		MmmMmmMmmMmm-1.16.5-1.2.0.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.2.0               |SIDED_SETU|NOSIGNATURE
		OffHandCombat-1.16.3-3.2.0.3.jar                  |Off Hand Combat               |offhandcombat                 |1.16.3-3.2.0.3      |SIDED_SETU|c9:84:cd:eb:27:ac:0d:ad:8c:55:6f:d6:5f:19:f2:c8:63:2a:b0:bd:3b:d0:b6:df:fd:9f:de:9f:9d:e8:7c:68
		twilightforest-1.16.5-4.0.482-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |SIDED_SETU|NOSIGNATURE
		supplementaries-1.16.5-0.12.2.jar                 |Supplementaries               |supplementaries               |1.16.5-0.12.2       |SIDED_SETU|NOSIGNATURE
		refinedstorage-1.9.12.jar                         |Refined Storage               |refinedstorage                |1.9.12              |SIDED_SETU|NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |SIDED_SETU|b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|NOSIGNATURE
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |SIDED_SETU|NOSIGNATURE
		ensorcellation-1.16.4-1.2.0.jar                   |Ensorcellation                |ensorcellation                |1.2.0               |SIDED_SETU|NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |SIDED_SETU|NOSIGNATURE
		TConstruct-1.16.5-3.0.4.171.jar                   |Tinkers' Construct            |tconstruct                    |3.0.4.171           |SIDED_SETU|NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |SIDED_SETU|NOSIGNATURE
		ForgeXray-1.0.5-1.16.x.jar                        |XrayMod                       |atianxray                     |1.0.5               |ERROR     |NOSIGNATURE
		silent-lib-1.16.3-4.9.6.jar                       |Silent Lib                    |silentlib                     |4.9.6               |SIDED_SETU|NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.440-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.439   |SIDED_SETU|NOSIGNATURE
		behgameon-1.16.4-1.0.0.jar                        |Behgameon                     |behgameon                     |1.0.0               |SIDED_SETU|NOSIGNATURE
		MekanismAdditions-1.16.5-10.0.21.448.jar          |Mekanism: Additions           |mekanismadditions             |10.0.21             |SIDED_SETU|NOSIGNATURE
		Lollipop-1.16.4-3.2.6.jar                         |Lollipop                      |lollipop                      |3.2.6               |SIDED_SETU|NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |SIDED_SETU|NOSIGNATURE
		silent-gear-1.16.5-2.6.24.jar                     |Silent Gear                   |silentgear                    |2.6.24              |SIDED_SETU|NOSIGNATURE
		iafgear-1.16.3-1.0.2.jar                          |DragonGear                    |iafgear                       |1.16.3-1.0.2        |SIDED_SETU|NOSIGNATURE
		forbidden_arcanus-1.16.4-1.0.0.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.16.4-1.0.0        |SIDED_SETU|NOSIGNATURE
		ElenaiDodge2-1.16.X-1.0.9b.jar                    |Elenai Dodge 2                |elenaidodge2                  |1.0.9b              |SIDED_SETU|NOSIGNATURE
		Botania-1.16.4-414.jar                            |Botania                       |botania                       |1.16.4-414          |SIDED_SETU|NOSIGNATURE
		managear-1.16.3-2.2.3.jar                         |Mana Gear                     |managear                      |1.16.3-2.2.3        |SIDED_SETU|NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |SIDED_SETU|NOSIGNATURE
		jousting-1.16.5-v1.0.3.jar                        |Jousting                      |jousting                      |1.16.5-v1.0.3       |SIDED_SETU|NOSIGNATURE
		simplybackpacks-1.16.3-1.4.13.jar                 |Simply Backpacks              |simplybackpacks               |1.16.3-1.4.13       |SIDED_SETU|NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.2.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |SIDED_SETU|NOSIGNATURE
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |SIDED_SETU|NOSIGNATURE
		playerex-1.1.8-1.16.5.jar                         |Player Ex                     |playerex                      |1.1.8               |SIDED_SETU|NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |SIDED_SETU|NOSIGNATURE
		Artifacts-1.16.4-2.7.5.jar                        |Artifacts                     |artifacts                     |1.16.4-2.7.5        |SIDED_SETU|NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |SIDED_SETU|NOSIGNATURE
		Origins-1.16.5-0.7.3.1-forge.jar                  |Origins                       |origins                       |0.7.3.1             |SIDED_SETU|NOSIGNATURE
		Mantle-1.16.5-1.6.103.jar                         |Mantle                        |mantle                        |1.6.103             |SIDED_SETU|NOSIGNATURE
		Xaeros_Minimap_21.10.0.3_Forge_1.16.5.jar         |Xaero's Minimap               |xaerominimap                  |21.10.0.3           |SIDED_SETU|NOSIGNATURE
		rats-7.2.0-1.16.5.jar                             |Rats                          |rats                          |7.2.0               |SIDED_SETU|NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |SIDED_SETU|NOSIGNATURE
		AutoRegLib-1.6-47 (3).jar                         |AutoRegLib                    |autoreglib                    |1.6-47              |SIDED_SETU|NOSIGNATURE
		time-in-a-bottle-1.1.0.jar                        |Time In A Bottle              |tiab                          |1.1.0               |SIDED_SETU|NOSIGNATURE
		angelring-1.16.5-1.3.4.1.jar                      |Angel Ring                    |angelring                     |1.3.4.1             |SIDED_SETU|NOSIGNATURE
		tombstone-1.16-6.2.5.jar                          |Corail Tombstone              |tombstone                     |1.16-6.2.5          |SIDED_SETU|NOSIGNATURE
		Quark-r2.4-305.jar                                |Quark                         |quark                         |r2.4-305            |SIDED_SETU|NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |SIDED_SETU|NOSIGNATURE
		architectury-1.17.20-forge.jar                    |Architectury                  |architectury                  |1.17.20             |SIDED_SETU|NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |SIDED_SETU|NOSIGNATURE
		ftb-chunks-1605.2.3-build.75.jar                  |FTB Chunks                    |ftbchunks                     |1605.2.3-build.75   |SIDED_SETU|NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |SIDED_SETU|NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |SIDED_SETU|NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.3.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |SIDED_SETU|NOSIGNATURE
		treasure-bags-1.16.3-1.4.0.jar                    |Treasure Bags                 |treasurebags                  |1.4.0               |SIDED_SETU|NOSIGNATURE
		SilentGems-1.16.3-3.7.15.jar                      |Silent's Gems 3               |silentgems                    |3.7.15              |SIDED_SETU|NOSIGNATURE
		Cyclic-1.16.5-1.2.8.jar                           |Cyclic                        |cyclic                        |1.16.5-1.2.8        |SIDED_SETU|1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: f803c581-4f24-4663-b899-82bbf7199475
	OptiFine Version: OptiFine_1.16.4_HD_U_G6
	OptiFine Build: 20210117-001622
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8681
	OpenGlRenderer: Intel(R) UHD Graphics 610
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by ate47** [comment]
Duplicate with #19
