### ISSUE TITLE
Forge version exception

### ISSUE THREAD

**Issue by Alceatraz** [ate47/Xray#24]
Game 1.16.5
Forge 36.1.32
Opti G8

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:378) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
-- MOD atianxray --
Details:
	Mod File: hack_ForgeXray-1.0.5-1.16.x.jar
	Failure message: XrayMod (atianxray) encountered an error during the common_setup event phase
		java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	Mod Version: 1.0.5
	Mod Issue URL: https://github.com/ate47/Xray/issues
	Exception message: java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
Stacktrace:
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:378) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:322) ~[lwjgl-opengl-3.2.2.jar:build 10] {}
	at com.jozufozu.flywheel.backend.Backend.refresh(Backend.java:148) ~[flywheel:1.16-0.1.1] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.handler$zbp000$refresh(WorldRenderer.java:6650) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:APP:cgm.mixins.json:client.WorldRendererMixin,pl:mixin:APP:mixins.baritone.json:MixinWorldRenderer,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:APP:appliedenergistics2.mixins.json:spatial.SkyRenderMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_72712_a(WorldRenderer.java:997) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.markForRerender,pl:mixin:APP:cgm.mixins.json:client.WorldRendererMixin,pl:mixin:APP:mixins.baritone.json:MixinWorldRenderer,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:APP:appliedenergistics2.mixins.json:spatial.SkyRenderMixin,pl:mixin:A}
	at fr.atesab.xray.XrayMain.modules(XrayMain.java:150) ~[atianxray:1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at fr.atesab.xray.XrayMain.saveConfigs(XrayMain.java:349) ~[atianxray:1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at fr.atesab.xray.XrayMain.loadConfigs(XrayMain.java:272) ~[atianxray:1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at fr.atesab.xray.XrayMain.setup(XrayMain.java:463) ~[atianxray:1.0.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

**Comment by ate47** [comment]
Duplicate #19

**Comment by sojakai** [comment]
Still Relevant as of 07/31/21. Waiting on update for 1.16.5
