### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'xray'!

### ISSUE THREAD

**Issue by DLandDS** [ate47/Xray#27]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 8/24/21 7:23 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'xray'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Boolean
	at fr.atesab.xray.XrayMain.loadConfigs(XrayMain.java:252)
	at fr.atesab.xray.XrayMain.onInitializeClient(XrayMain.java:446)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 450157568 bytes (429 MB) / 1012924416 bytes (966 MB) up to 1012924416 bytes (966 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Fabric Mods: 
		appleskin: AppleSkin mc1.16.4-2.1.3
		architectury: Architectury 1.21.31
		autoclicker-fabric: Auto Clicker 1.16.5-1.0.2-build.12
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoreconnect: AutoReconnect 1.1.0
		blockmeter: Block Meter 1.16.3-fabric0.20.2-1.5.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.26
		com_github_kaptainwutax_biomeutils: BiomeUtils 62b374f2def7e09240447aceeb12a0a601b59a2b
		com_github_kaptainwutax_chunkrandomreversal: ChunkRandomReversal 209eefb8ed2bd097e3c55d3934ba508b664443da
		com_github_kaptainwutax_featureutils: FeatureUtils 0bd98a8dd892ff8d7292bcf5545f79a91a5eecca
		com_github_kaptainwutax_latticg: LattiCG b2a338f7bd765dcd184136c2245ea5765b75edf8
		com_github_kaptainwutax_mathutils: MathUtils 6c2d50eacad0241ff76119e6e703b70bac4b4bce
		com_github_kaptainwutax_seedutils: SeedUtils 0de70bc772fef95d8acfa6991e7278ee53a8b46c
		com_seedfinding_latticg: latticg 1.5
		completeconfig: CompleteConfig 0.17.1
		fabric: Fabric API 0.38.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2b6fb8d77d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+efd7b8cf7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+95b14da07d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+5badb62d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+5badb62d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f3e8589e7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+6afaa13c7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+83a7653f7d
		fabricloader: Fabric Loader 0.11.6
		fiber: fiber 0.23.0-2
		fpsdisplay: FPS-Display 1.4.1+1.16.4
		hydrogen: Hydrogen 0.2
		inventoryhud: Inventory HUD + 3.4.0
		iris: Iris 1.1.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lambdabettergrass: LambdaBetterGrass 1.0.3+1.16
		lambdacontrols: LambdaControls 1.6.0+1.16
		lightoverlay: Light Overlay 5.8.0
		litematica: Litematica 0.0.0-dev.20210612.170003
		lithium: Lithium 0.6.6
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.12
		multiconnect: MultiConnect 1.3.36
		multiconnect-api: MultiConnect API 1.3.36
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		seedcrackerx: Seed Cracker X 0.2.7
		shieldisruptor: Shield Disruptor 1.3.0+1.16.5
		sodium: Sodium 0.2.0+IRIS3-build.49
		spruceui: SpruceUI 2.1.4+1.16
		torohealth: ToroHealth Damage Indicators 1.16.5-fabric-6
		uglyscoreboardfix: Ugly Scoreboard Fix 2.2.2
		wthit: wthit 2.10.2
		xaerominimap: Xaero's Minimap 21.15.1
		xaeroworldmap: Xaero's World Map 1.16.1
		xray: XrayMod 1.0.6
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by ate47** [comment]
Can you delete the xray.json file in the .minecraft directory and restart your game?

**Comment by DLandDS** [comment]
That's solve the problem.
i was trying to copy the config file to older version.
it looks like the format config changed i think. that's why it crashed.
Thank you.
