### ISSUE TITLE
matlilib xray 1.13.2 incompatibility

### ISSUE THREAD

**Issue by Elsys656** [ate47/Xray#3]
version xray 1.0.3-1.13.2 crashes if you also have matlilib [0.9.3] which is needed by mods like 'rift-modlist' (using 'Rift d6893ec777' fork & 'MultiMC' launcher BTW)

 

Can verify this the log complains about matlilib hooking into minecrafts GUILib which this mod apparently already does. Basically what I can gather is that matlilib's method of dealing with hotkeys and this one are incompatible. Voxelmap works however since its closed I cannot see how they did their hotkeys. Probably in the adding of hotkey options within the keybinds window. There is a configuration file for matlilib where you can blacklist keys for it to listen to. I might try and add those keys used by this and see if that resolves the issue but I think its deeper than that.

 

Mixin prepare failed preparing MixinGuiScreen in mixins.malilib.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.malilib.json:MixinGuiScreen target ckd was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.malilib.json:MixinGuiScreen target ckd was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ate47** [comment]
The 1.13 won’t be updated anymore
