### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by Sennixx** [ate47/Xray#31]
1 error has occurred during loading

**To Reproduce**
Just launch the game

**Minecraft version**
Minecraft version: 1.18.1
Mod loader (Fabric/Forge/Rift):  Forge
Mod on its own

**Additional context**
Worked fine yesterday but its crashing today, no clue why.

from crashlog:

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2322!:?] {}
-- MOD atianxray --
Details:
	Caused by 0: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 146 column 3 path $
		at com.google.gson.Gson.assertFullConsumption(Gson.java:908) ~[gson-2.8.8.jar%2322!:?] {}
		at com.google.gson.Gson.fromJson(Gson.java:871) ~[gson-2.8.8.jar%2322!:?] {}
		at fr.atesab.xray.XrayMain.loadConfigs(XrayMain.java:286) ~[XrayMod-1.2.1%20(1).jar%2353!:1.2.1] {re:mixin,re:classloading}
		at fr.atesab.xray.XrayMain.setup(XrayMain.java:494) ~[XrayMod-1.2.1%20(1).jar%2353!:1.2.1] {re:mixin,re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.0.jar%2356!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.0.jar%2355!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: XrayMod-1.2.1 (1).jar
	Failure message: XrayMod (atianxray) encountered an error during the common_setup event phase
		com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 146 column 3 path $
	Mod Version: 1.2.1
	Mod Issue URL: https://github.com/ate47/Xray/issues
	Exception message: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 146 column 3 path $
Stacktrace:
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:541) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.assertFullConsumption(Gson.java:904) ~[gson-2.8.8.jar%2322!:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:871) ~[gson-2.8.8.jar%2322!:?] {}
	at fr.atesab.xray.XrayMain.loadConfigs(XrayMain.java:286) ~[XrayMod-1.2.1%20(1).jar%2353!:1.2.1] {re:mixin,re:classloading}
	at fr.atesab.xray.XrayMain.setup(XrayMain.java:494) ~[XrayMod-1.2.1%20(1).jar%2353!:1.2.1] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.0.jar%2356!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.0.jar%2355!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by ate47** [comment]
Can you try to delete the xray.json file in your .minecraft? And relaunch twice the game?

**Comment by ate47** [comment]
It should be fixed.
