### ISSUE TITLE
XrayMod (atianxray) encountered an error during the common_setup event phase / JSON document was not fully consumed.

### ISSUE THREAD

**Issue by Jessman5** [ate47/Xray#35]
**Describe the bug**
crashes game.

**To Reproduce**
start the game.

**Crash report or logs**
[28/12/2021 11:03:30 AM] A detailed walkthrough of the error, its code path and all known details is as follows:
[28/12/2021 11:03:30 AM] ---------------------------------------------------------------------------------------
[28/12/2021 11:03:30 AM] 
[28/12/2021 11:03:30 AM] -- Head --
[28/12/2021 11:03:30 AM] Thread: Render thread
[28/12/2021 11:03:30 AM] Stacktrace:
[28/12/2021 11:03:30 AM] 	at com.google.gson.Gson.assertFullConsumption(Gson.java:905) ~[gson-2.8.8.jar%2322!:?] {}
[28/12/2021 11:03:30 AM] -- MOD atianxray --
[28/12/2021 11:03:30 AM] Details:
[28/12/2021 11:03:30 AM] 	Mod File: xray-1.2.2-forge-1.18.1.jar
[28/12/2021 11:03:30 AM] 	Failure message: XrayMod (atianxray) encountered an error during the common_setup event phase
[28/12/2021 11:03:30 AM] 		com.google.gson.JsonIOException: JSON document was not fully consumed.
[28/12/2021 11:03:30 AM] 	Mod Version: 1.2.2
[28/12/2021 11:03:30 AM] 	Mod Issue URL: https://github.com/ate47/Xray/issues
[28/12/2021 11:03:30 AM] 	Exception message: com.google.gson.JsonIOException: JSON document was not fully consumed.
[28/12/2021 11:03:30 AM] Stacktrace:
[28/12/2021 11:03:30 AM] 	at com.google.gson.Gson.assertFullConsumption(Gson.java:905) ~[gson-2.8.8.jar%2322!:?] {}
[28/12/2021 11:03:30 AM] 	at com.google.gson.Gson.fromJson(Gson.java:871) ~[gson-2.8.8.jar%2322!:?] {}
[28/12/2021 11:03:30 AM] 	at fr.atesab.xray.XrayMain.loadConfigs(XrayMain.java:287) ~[xray-1.2.2-forge-1.18.1.jar%2389!:1.2.2] {re:mixin,re:classloading}
[28/12/2021 11:03:30 AM] 	at fr.atesab.xray.XrayMain.setup(XrayMain.java:496) ~[xray-1.2.2-forge-1.18.1.jar%2389!:1.2.2] {re:mixin,re:classloading}
[28/12/2021 11:03:30 AM] 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
[28/12/2021 11:03:30 AM] 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
[28/12/2021 11:03:30 AM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
[28/12/2021 11:03:30 AM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
[28/12/2021 11:03:30 AM] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.9.jar%2392!:?] {}
[28/12/2021 11:03:30 AM] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.9.jar%2391!:?] {}
[28/12/2021 11:03:30 AM] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[28/12/2021 11:03:30 AM] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[28/12/2021 11:03:30 AM] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[28/12/2021 11:03:30 AM] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[28/12/2021 11:03:30 AM] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
[28/12/2021 11:03:30 AM] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
[28/12/2021 11:03:30 AM] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Minecraft version**
Minecraft version: 1.18.1
Mod loader (Fabric/Forge/Rift): 39.0.9

**Comment by ate47** [comment]
Duplicate with #32
